"""
journey_narrator.py
===================
Phase 11 — Final LLM pass: validates path coherence, generates human-readable
narrative for each of the 3 paths, and builds the visualization tree JSON that
the frontend renders as the branching tree (root → main branches → twigs).

Uses qwen/qwen3.5-122b-a10b (thinking ON) for the highest-quality final output.

Visualization semantics:
  - root node        : role goal (largest bubble, bold)
  - main branch node : critical/moderate gap skill (medium bubble, coloured border)
  - twig node        : dependency/prerequisite skill that feeds into a main branch
  - edge thickness   : proportional to gap severity (critical > moderate)

Emits Redis events: journey | start → journey | result
"""

import json
import re
from typing import Dict, List, Optional

from app.clients.nvidia_llm_client import narrator_llm_client   # qwen3.5-122b thinking
from app.clients.redis_client import redis_client
from app.utils.logger import logger

# ── Prompt ────────────────────────────────────────────────────────────────────
_NARRATOR_PROMPT = """You are an expert career coach and learning architect. You have been given 3 alternative learning paths generated by a multi-objective optimisation algorithm for an employee with specific skill gaps.

Your tasks:
1. VALIDATE each path for coherence — does the stage ordering make sense? Are there obvious logical errors?
2. WRITE a 2-sentence narrative description for each path (Sprint, Balanced, Quality) that a non-technical HR manager can understand.
3. BUILD a visualization tree JSON that the frontend will render as an interactive branching tree.

VISUALIZATION TREE RULES:
- "root" node = the target role title (type: "role_goal", size: "large")
- "main_branch" node = each critical/moderate gap skill (type: "main_branch", size: "medium")
  - border_color: "#EF4444" for critical, "#F59E0B" for moderate
- "twig" node = prerequisite skills that feed INTO a main branch skill (type: "twig", size: "small")
  - These come from the dependency_edges list
- Each "main_branch" node must include "course_options" with sprint/balanced/quality course titles and durations
- Nodes with NO prerequisites are connected directly to the root

OUTPUT FORMAT — return ONLY this JSON (no markdown fences, no extra text):
{{
  "validation": {{
    "sprint_ok":   true,
    "balanced_ok": true,
    "quality_ok":  true,
    "notes": "One sentence about any concerns, or 'All paths are coherent.'"
  }},
  "narratives": {{
    "sprint":   "2-sentence description of Sprint path for HR manager.",
    "balanced": "2-sentence description of Balanced path for HR manager.",
    "quality":  "2-sentence description of Quality path for HR manager."
  }},
  "tree": {{
    "root": {{
      "id": "root",
      "type": "role_goal",
      "label": "<role title here>",
      "size": "large",
      "children": [
        {{
          "id": "skill_<slug>",
          "type": "main_branch",
          "label": "<skill name>",
          "severity": "critical",
          "size": "medium",
          "border_color": "#EF4444",
          "stage": 1,
          "gap": 0.55,
          "children": [
            {{
              "id": "twig_<slug>",
              "type": "twig",
              "label": "<prerequisite skill>",
              "size": "small",
              "depends_on": "<main branch skill it feeds into>"
            }}
          ],
          "course_options": {{
            "sprint":   {{"title": "...", "duration": "...", "institution": "...", "rating": 0.0}},
            "balanced": {{"title": "...", "duration": "...", "institution": "...", "rating": 0.0}},
            "quality":  {{"title": "...", "duration": "...", "institution": "...", "rating": 0.0}}
          }}
        }}
      ]
    }}
  }},
  "path_summaries": {{
    "sprint":   {{"total_weeks": 0, "coverage_score": 0.0, "label": "Sprint Track"}},
    "balanced": {{"total_weeks": 0, "coverage_score": 0.0, "label": "Balanced Track"}},
    "quality":  {{"total_weeks": 0, "coverage_score": 0.0, "label": "Quality Track"}}
  }}
}}

---
INPUT DATA:

Role Title: {role_title}

SPRINT PATH:
{sprint_path_json}

BALANCED PATH:
{balanced_path_json}

QUALITY PATH:
{quality_path_json}

DEPENDENCY EDGES (skill prerequisites):
{edges_json}

PATH STATISTICS:
{stats_json}

Now produce the complete JSON output:"""


def _slugify(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")


def _parse_narrator(raw: str) -> Optional[Dict]:
    """
    Cleans and parses the LLM output. Qwen and other 100k+ models sometimes
    include CoT or conversational text even in content. This finds the LAST
    JSON object in the string to maximize likelihood of getting the final answer.
    """
    # 1. Basic markdown stripping
    clean = re.sub(r"```(?:json)?", "", raw).strip().rstrip("`").strip()

    # 2. Try direct load
    try:
        return json.loads(clean)
    except json.JSONDecodeError:
        pass

    # 3. Find LAST JSON block (matches outer {} pairs)
    # Using a negative lookahead to skip over text before the final object
    # This is more robust for models that "summarize" their JSON at the end
    matches = list(re.finditer(r"\{(?:[^{}]|(?R))*\}", clean))
    if matches:
        # Try from end to start
        for m in reversed(matches):
            try:
                candidate = m.group()
                return json.loads(candidate)
            except json.JSONDecodeError:
                continue

    # 4. Fallback: broad search for any JSON-like structure
    match = re.search(r"\{[\s\S]+\}", clean)
    if match:
        try:
            return json.loads(match.group())
        except json.JSONDecodeError:
            pass

    return None


def _build_fallback_tree(
    role_title: str,
    sprint_path: List[Dict],
    balanced_path: List[Dict],
    quality_path: List[Dict],
    edges: List[Dict],
    sprint_stats: Dict,
    balanced_stats: Dict,
    quality_stats: Dict,
) -> Dict:
    """
    Builds a minimal valid tree JSON without LLM — used as fallback if the
    LLM call fails or returns unparseable output.
    """
    children = []
    # Index paths by skill name
    sprint_idx   = {e["skill"]: e for e in sprint_path}
    balanced_idx = {e["skill"]: e for e in balanced_path}
    quality_idx  = {e["skill"]: e for e in quality_path}

    # Collect twig skills per main-branch skill from edges
    twig_map: Dict[str, List[str]] = {}
    for edge in edges:
        target = edge.get("to", "")
        source = edge.get("from", "")
        twig_map.setdefault(target, []).append(source)

    seen_skills = set()
    for entry in sprint_path:
        skill = entry["skill"]
        if skill in seen_skills:
            continue
        seen_skills.add(skill)

        severity = entry.get("gap_category", "moderate")
        border   = "#EF4444" if severity == "critical" else "#F59E0B"
        gap      = round(
            (entry.get("target_mastery", 0.5) - entry.get("current_mastery", 0.0)),
            3,
        )

        def _course_summary(entry_map: Dict, s: str) -> Optional[Dict]:
            e = entry_map.get(s)
            if not e or not e.get("course"):
                return None
            c = e["course"]
            return {
                "title":       c.get("title", ""),
                "duration":    c.get("duration_label", ""),
                "institution": c.get("institution", ""),
                "rating":      c.get("rate", 0.0),
            }

        twigs = [
            {
                "id":         f"twig_{_slugify(dep)}",
                "type":       "twig",
                "label":      dep,
                "size":       "small",
                "depends_on": skill,
            }
            for dep in twig_map.get(skill, [])
        ]

        children.append({
            "id":           f"skill_{_slugify(skill)}",
            "type":         "main_branch",
            "label":        skill,
            "severity":     severity,
            "size":         "medium",
            "border_color": border,
            "stage":        entry.get("stage", 1),
            "gap":          gap,
            "children":     twigs,
            "course_options": {
                "sprint":   _course_summary(sprint_idx,   skill),
                "balanced": _course_summary(balanced_idx, skill),
                "quality":  _course_summary(quality_idx,  skill),
            },
        })

    return {
        "validation": {"sprint_ok": True, "balanced_ok": True, "quality_ok": True, "notes": "Fallback tree — LLM narration unavailable."},
        "narratives": {
            "sprint":   f"The Sprint Track completes all required training in approximately {sprint_stats.get('total_weeks', 0)} weeks using the shortest available courses.",
            "balanced": f"The Balanced Track takes approximately {balanced_stats.get('total_weeks', 0)} weeks, offering the best trade-off between speed and relevance.",
            "quality":  f"The Quality Track invests {quality_stats.get('total_weeks', 0)} weeks in the highest-rated, most comprehensive courses for each skill gap.",
        },
        "tree": {
            "root": {
                "id":       "root",
                "type":     "role_goal",
                "label":    role_title,
                "size":     "large",
                "children": children,
            }
        },
        "path_summaries": {
            "sprint":   {**sprint_stats,   "label": "Sprint Track"},
            "balanced": {**balanced_stats, "label": "Balanced Track"},
            "quality":  {**quality_stats,  "label": "Quality Track"},
        },
    }


async def narrate_journey(
    role_title: str,
    path_result: Dict,
    role_id: str,
) -> Dict:
    """
    Main entry point called from orchestrator.py Phase 11.

    path_result: output of path_generator.generate_paths()
    Returns the full journey object including tree JSON and narratives.
    """
    sprint_path   = path_result.get("sprint_path", [])
    balanced_path = path_result.get("balanced_path", [])
    quality_path  = path_result.get("quality_path", [])
    edges         = path_result.get("dependency_edges", [])
    sprint_stats  = path_result.get("sprint_stats",  {"total_weeks": 0, "coverage_score": 0.0})
    balanced_stats= path_result.get("balanced_stats",{"total_weeks": 0, "coverage_score": 0.0})
    quality_stats = path_result.get("quality_stats", {"total_weeks": 0, "coverage_score": 0.0})

    await redis_client.publish_event(
        role_id=role_id,
        phase="journey",
        event_type="start",
        step="narrator_start",
        message="Building final learning journey and visualization tree",
        data={"role": role_title, "skills": len(sprint_path)},
    )

    def _serialize_path(path: List[Dict]) -> str:
        slim = []
        for e in path:
            c = e.get("course") or {}
            slim.append({
                "stage":           e.get("stage"),
                "skill":           e.get("skill"),
                "gap_category":    e.get("gap_category"),
                "target_mastery":  e.get("target_mastery"),
                "current_mastery": e.get("current_mastery"),
                "course": {
                    "title":         c.get("title", "N/A"),
                    "institution":   c.get("institution", ""),
                    "duration":      c.get("duration_label", ""),
                    "level":         c.get("level", ""),
                    "rating":        c.get("rate", 0.0),
                    "cosine_sim":    c.get("cosine_sim", 0.0),
                } if c else None,
            })
        return json.dumps(slim, ensure_ascii=False, indent=2)

    prompt = _NARRATOR_PROMPT.format(
        role_title=role_title,
        sprint_path_json=_serialize_path(sprint_path),
        balanced_path_json=_serialize_path(balanced_path),
        quality_path_json=_serialize_path(quality_path),
        edges_json=json.dumps(edges, ensure_ascii=False),
        stats_json=json.dumps({
            "sprint":   sprint_stats,
            "balanced": balanced_stats,
            "quality":  quality_stats,
        }, ensure_ascii=False, indent=2),
    )

    reasoning, content = await narrator_llm_client.stream(
        prompt=prompt,
        temperature=0.6,    # Qwen prefers slightly higher temp for narration
        max_tokens=24000,   # qwen3.5-122b handles long thinking traces
        role_id=role_id,
        phase="journey",
        step_name="narrator_llm_stream",
    )

    journey = _parse_narrator(content)

    if not journey:
        logger.warning("[JourneyNarrator] LLM parse failed — using fallback tree builder.")
        journey = _build_fallback_tree(
            role_title, sprint_path, balanced_path, quality_path,
            edges, sprint_stats, balanced_stats, quality_stats,
        )

    # Attach the raw paths for DB persistence
    journey["raw_paths"] = {
        "sprint":   sprint_path,
        "balanced": balanced_path,
        "quality":  quality_path,
    }
    journey["gap_options"] = path_result.get("gap_options", {})

    await redis_client.publish_event(
        role_id=role_id,
        phase="journey",
        event_type="result",
        step="journey_ready",
        message="Learning journey complete — 3 paths available",
        data={
            "validation":     journey.get("validation", {}),
            "narratives":     journey.get("narratives", {}),
            "tree":           journey.get("tree", {}),
            "path_summaries": {
                "sprint":   {**sprint_stats,   "label": "Sprint Track"},
                "balanced": {**balanced_stats, "label": "Balanced Track"},
                "quality":  {**quality_stats,  "label": "Quality Track"},
            },
            "tree_nodes":     len(journey.get("tree", {}).get("root", {}).get("children", [])),
        },
    )

    return journey
